version: '3'
services:

  # Build app from Dockerfile in same folder
  app:
    build: .

  # Build the db as name db from the Dockerfile in the db folder
  db:
    build: db/.
    ports:
      - "3307:3306"
